"use client";
import { useEffect, useState } from "react";
import { Check, Eye, RotateCcw, Trash2 } from "lucide-react";
import { calculateCalendarWeekMetrics, canConfirm, effectiveValues, groupingDate, type TransactionLifecycle } from "../domain/transaction-lifecycle";
import type { TransactionKind } from "../domain/transaction-candidate";
import { EMPTY_REVIEW_SNAPSHOT, isReplaySuppressed, parseSnapshot, removeEventPermanently, serializeSnapshot, type ReviewSnapshot } from "../domain/review-persistence";

const KEY = "fictional-finance-review-v1", WEEK = "2026-09-21";
const kinds: TransactionKind[] = ["purchase", "income", "refund", "reversal", "withdrawal", "transfer", "unknown"];
function record(id:string, label:string, amountMinor:number, currency:string|undefined, eventType:TransactionKind, date?:string, extra:Partial<TransactionLifecycle>={}) : TransactionLifecycle {
 const captureId=`fixture-${id}`, sourceIdentity=`fictional-mail:${id}`;
 return {id:`event:${id}`,sourceIdentity,sourceCandidates:[{candidateId:`candidate:${captureId}`,captureId,capturedAt:"2026-09-22T09:30:00Z",processedAt:"2026-09-22T09:31:00Z",status:"detected",reviewStatus:"pending",sourceFacts:{amountMinor,...(currency&&{currency}),...(date&&{occurredAt:date}),merchantText:label,kind:eventType,evidence:[{field:"amount",excerpt:currency?`${currency} ${(amountMinor/100).toFixed(2)}`:`${(amountMinor/100).toFixed(2)}`},{field:"merchantText",excerpt:label},...(date?[{field:"occurredAt" as const,excerpt:date}]:[]),{field:"kind",excerpt:eventType==="unknown"?"payment completed":eventType}]},inferred:{reviewReason:eventType==="unknown"?"The source does not establish direction.":undefined}}],sourceProvenance:[{captureId,sourceIdentity,sourceType:"fixture",provider:"fictional-mail",sourceEventId:id}],interpretation:{amountMinor,...(currency&&{currency}),merchantText:label,...(date&&{occurredAt:date}),eventType,settlementState:"unknown"},userOverrides:{},confirmationState:"needs_confirmation",disposition:"active",deletionState:"active",relationships:[],attentionReasons:[...(currency?[]:["missing_currency"]),...(eventType==="unknown"?["ambiguous_classification"]:[])],...extra};
}
const seed=[record("coffee-001","Blue Kettle Cafe",1299,"EUR","purchase","2026-09-22"),record("mystery-002","Payment notice from fictional provider",1750,"EUR","unknown"),record("transit-003","City transit payment",420,undefined,"purchase","2026-09-23"),record("coffee-copy-004","Blue Kettle Cafe",1299,"EUR","purchase","2026-09-22",{relationships:[{kind:"possible_duplicate_of",targetId:"event:coffee-001",reasons:["same_amount","same_currency","same_event_type","same_normalized_merchant"]}],attentionReasons:["possible_duplicate"]})];
const initial=():ReviewSnapshot=>({...EMPTY_REVIEW_SNAPSHOT,records:seed});
const money=(n:number,c:string)=>new Intl.NumberFormat("en",{style:"currency",currency:c}).format(n/(c==="JPY"?1:100));

export default function Home(){
 const [snapshot,setSnapshot]=useState<ReviewSnapshot>(()=>typeof window === "undefined" ? initial() : parseSnapshot(localStorage.getItem(KEY))??initial()),[selectedId,setSelectedId]=useState(seed[0].id),[editing,setEditing]=useState(false),[preview,setPreview]=useState(false),[note,setNote]=useState("");
 useEffect(()=>{localStorage.setItem(KEY,serializeSnapshot(snapshot))},[snapshot]);
 const records=snapshot.records, selected=records.find(x=>x.id===selectedId)??records[0], metrics=calculateCalendarWeekMetrics(records,WEEK), summary=metrics.byCurrency[0];
 const eligible=records.filter(canConfirm), routine=eligible.filter(x=>!x.attentionReasons.length&&!x.relationships.length);
 const update=(id:string,f:(x:TransactionLifecycle)=>TransactionLifecycle)=>setSnapshot(s=>({...s,records:s.records.map(x=>x.id===id?f(x):x)}));
 const replay=()=>{setSnapshot(s=>({...s,records:[...s.records,...seed.filter(x=>!s.records.some(y=>y.id===x.id)&&!isReplaySuppressed(s,{captureId:x.sourceCandidates[0].captureId,sourceType:"fixture",provider:"fictional-mail",rawText:"fictional",metadata:{externalId:x.sourceProvenance[0].sourceEventId}}))]}));setNote("Replay finished. Existing events and deletion markers stop double counting and resurrection.")};
 if(!selected)return <main className="p-6">All fictional events were deleted. Replay does not restore events with suppression markers.</main>;
 const v=effectiveValues(selected), grouped=groupingDate(selected);
 return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-5xl p-4 sm:p-7"><header className="mb-6 flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Fictional-data review demo</p><h1 className="text-2xl font-bold">Review detected activity</h1><p className="mt-1 max-w-2xl text-sm text-slate-600">Detected activity is not a balance, account view, or complete finances.</p></div><button onClick={replay} className="rounded border px-3 py-2 text-sm font-semibold"><RotateCcw className="mr-1 inline h-4"/>Replay fixtures</button></header>
 {summary&&<section className="mb-5 rounded-xl border border-teal-200 bg-white p-4"><h2 className="font-bold">Calendar week {WEEK} to 2026-09-27 · {summary.currency}</h2><p className="text-xs text-slate-500">UTC is the fictional demo grouping convention, not a future timezone policy.</p><div className="mt-3 grid grid-cols-3 gap-3 text-sm"><p><b>{money(summary.detectedInflowMinor,summary.currency)}</b><br/><span className="text-xs">detected inflow</span></p><p><b>{money(summary.detectedOutflowMinor,summary.currency)}</b><br/><span className="text-xs">detected outflow</span></p><p><b>{money(summary.detectedNetFlowMinor,summary.currency)}</b><br/><span className="text-xs">detected net flow</span></p></div><p className="mt-2 text-sm text-amber-800">Pending: {summary.awaitingConfirmation.count}. Provisional assumed outflow: {money(summary.provisionalOutflowMinor,summary.currency)}. Missing-currency candidates: {metrics.unaggregatedActiveCount}. Coverage: four fictional notices.</p></section>}
 <section className="mb-5 rounded-xl border bg-white p-4"><b>Fast review</b><p className="mt-1 text-sm text-slate-600">Routine approval confirms {routine.length} eligible item(s); it never invents currency, classifies unknown events, or decides duplicates.</p><div className="mt-3 flex gap-2"><button onClick={()=>{setSnapshot(s=>({...s,records:s.records.map(x=>routine.some(y=>y.id===x.id)?{...x,confirmationState:"confirmed"}:x)}));setNote(`Confirmed ${routine.length} routine candidate(s).`)}} className="rounded bg-teal-700 px-3 py-2 text-sm font-bold text-white">Confirm routine eligible ({routine.length})</button><button onClick={()=>setPreview(true)} className="rounded border px-3 py-2 text-sm font-semibold">Preview all eligible ({eligible.length})</button></div></section>
 <div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><section className="rounded-xl border bg-white p-3"><h2 className="px-2 pb-2 font-bold">Candidates</h2>{records.map(x=>{const z=effectiveValues(x);return <button key={x.id} onClick={()=>{setSelectedId(x.id);setEditing(false)}} className={`mb-2 w-full rounded border p-3 text-left ${selectedId===x.id?"border-teal-600 bg-teal-50":"border-slate-200"}`}><b className="text-sm">{z.merchantText}</b><p className="text-xs">{z.amountMinor!==undefined&&z.currency?money(z.amountMinor,z.currency):"currency missing"} · {z.eventType} · {x.confirmationState}</p>{x.attentionReasons.length>0&&<p className="text-xs text-amber-700">Needs attention: {x.attentionReasons.join(", ")}</p>}</button>})}</section>
 <section className="rounded-xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Candidate detail</p><h2 className="text-xl font-bold">{v.merchantText}</h2><div className="mt-3 space-y-1 text-sm"><p><b>Amount:</b> {v.amountMinor!==undefined?(v.currency?money(v.amountMinor,v.currency):`${v.amountMinor/100} (currency missing)`):"missing"} · {selected.userOverrides.currency||selected.userOverrides.amountMinor?"edited by you / user rule":"explicit source"}</p><p><b>Date:</b> {grouped.value??"missing"} · {grouped.basis.replaceAll("_"," ")}</p><p><b>Type:</b> {v.eventType}{v.eventType==="unknown"&&" — provisional assumption; classify before confirming"}</p><p><b>Impact:</b> {selected.disposition==="excluded"?"excluded from detected flow":v.eventType==="unknown"?"separate provisional outflow":"included once in detected flow"}</p></div>
 <details className="mt-4 rounded bg-slate-50 p-3"><summary className="cursor-pointer font-semibold"><Eye className="mr-1 inline h-4"/>Source excerpt and later change evidence</summary><p className="mt-2 text-sm">{selected.sourceCandidates.flatMap(c=>c.sourceFacts.evidence.map(e=>`${e.field}: “${e.excerpt}”`)).join(" · ")}</p><p className="mt-2 text-xs text-slate-500">Later finalized evidence replaces the system reading (higher or lower), returns a material confirmed item to review, and preserves user edits.</p></details>
 {selected.relationships.some(r=>r.kind==="possible_duplicate_of")&&<div className="mt-4 rounded border border-amber-200 bg-amber-50 p-3 text-sm"><b>Possible duplicate:</b> both records remain counted. <div className="mt-2 flex gap-2"><button onClick={()=>update(selected.id,x=>({...x,relationships:x.relationships.map(r=>r.kind==="possible_duplicate_of"?{kind:"duplicate_of",targetId:r.targetId}:r)}))} className="rounded bg-amber-700 px-2 py-1 text-white">Same event</button><button onClick={()=>update(selected.id,x=>({...x,relationships:[],attentionReasons:[]}))} className="rounded border px-2 py-1">Separate events</button><button onClick={()=>setNote("Decide later: both records are still visible and counted twice.")} className="rounded border px-2 py-1">Decide later</button></div><p className="mt-2 text-xs">Choices are reversible; Same event suppresses only this displayed record’s impact.</p></div>}
 <div className="mt-5 flex flex-wrap gap-2">{selected.disposition==="active"?<button disabled={!canConfirm(selected)} onClick={()=>{update(selected.id,x=>({...x,confirmationState:"confirmed"}));setNote("Confirmed: accepts the displayed movement, not bank verification.")}} className="rounded bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:bg-slate-300"><Check className="mr-1 inline h-4"/>Confirm</button>:<button onClick={()=>update(selected.id,x=>({...x,disposition:"active"}))} className="rounded border px-3 py-2 text-sm font-bold">Restore exclusion</button>}<button onClick={()=>setEditing(!editing)} className="rounded border px-3 py-2 text-sm font-bold">Correct / comment</button>{selected.disposition==="active"&&<button onClick={()=>update(selected.id,x=>({...x,disposition:"excluded"}))} className="rounded border px-3 py-2 text-sm font-bold">Exclude</button>}<button onClick={()=>{if(confirm("Delete event and visible history? Only a minimal replay-suppression marker remains.")){setSnapshot(s=>removeEventPermanently(s,selected.id));setSelectedId(records.find(x=>x.id!==selected.id)?.id??"");setNote("Deleted event content and history. A minimal marker remains to stop source replay; this is not every trace erased.")}}} className="rounded border border-red-200 px-3 py-2 text-sm font-bold text-red-700"><Trash2 className="mr-1 inline h-4"/>Delete permanently</button></div>
 {editing&&<Editor record={selected} save={o=>{update(selected.id,x=>({...x,userOverrides:{...x.userOverrides,...o},confirmationState:"confirmed"}));setEditing(false);setNote("Saved and confirmed. Your changes remain separate from the source.")}} undo={f=>update(selected.id,x=>{const o={...x.userOverrides};delete o[f];return {...x,userOverrides:o}})}/>}</section></div>
 {preview&&<div className="fixed inset-0 grid place-items-center bg-slate-900/40 p-4"><div className="max-w-lg rounded-xl bg-white p-5"><h2 className="font-bold">Confirm all eligible?</h2><p className="mt-2 text-sm">{eligible.length} eligible. Flagged: {records.length-routine.length}. Possible duplicates may count twice; this does not settle them. Unknown types and missing currency remain pending.</p><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setPreview(false)} className="rounded border px-3 py-2">Cancel</button><button onClick={()=>{setSnapshot(s=>({...s,records:s.records.map(x=>canConfirm(x)?{...x,confirmationState:"confirmed"}:x)}));setPreview(false);setNote(`Confirmed ${eligible.length} eligible items; exceptions remain pending.`)}} className="rounded bg-teal-700 px-3 py-2 font-bold text-white">Confirm eligible</button></div></div></div>}{note&&<p className="fixed bottom-4 right-4 max-w-sm rounded bg-slate-900 p-3 text-sm text-white">{note}</p>}</div></main>;
}
function Editor({record,save,undo}:{record:TransactionLifecycle;save:(o:TransactionLifecycle["userOverrides"])=>void;undo:(f:keyof TransactionLifecycle["userOverrides"])=>void}){const v=effectiveValues(record);const[a,setA]=useState(v.amountMinor===undefined?"":String(v.amountMinor/100)),[c,setC]=useState(v.currency??""),[d,setD]=useState(v.occurredAt?.slice(0,10)??""),[k,setK]=useState<TransactionKind>(v.eventType),[l,setL]=useState(v.merchantText??""),[comment,setComment]=useState(record.userOverrides.comment??""),[category,setCategory]=useState(record.userOverrides.category??"");return <form onSubmit={e=>{e.preventDefault();save({...(a&&{amountMinor:Math.round(Number(a)*100)}),...(c&&{currency:c.toUpperCase()}),...(d&&{occurredAt:d}),eventType:k,merchantLabel:l,comment,category})}} className="mt-4 rounded border bg-slate-50 p-3 text-sm"><b>Correct fields (your edits)</b><div className="mt-2 grid gap-2 sm:grid-cols-2"><label>Amount<input value={a} onChange={e=>setA(e.target.value)} className="mt-1 w-full rounded border p-1"/></label><label>Currency<input value={c} onChange={e=>setC(e.target.value)} className="mt-1 w-full rounded border p-1"/></label><label>Date<input type="date" value={d} onChange={e=>setD(e.target.value)} className="mt-1 w-full rounded border p-1"/></label><label>Type<select value={k} onChange={e=>setK(e.target.value as TransactionKind)} className="mt-1 w-full rounded border p-1">{kinds.map(x=><option key={x}>{x}</option>)}</select></label><label>Display label<input value={l} onChange={e=>setL(e.target.value)} className="mt-1 w-full rounded border p-1"/></label><label>Category<input value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded border p-1"/></label></div><label className="mt-2 block">Optional comment<textarea value={comment} onChange={e=>setComment(e.target.value)} className="mt-1 w-full rounded border p-1"/></label><div className="mt-3 flex flex-wrap gap-2"><button className="rounded bg-teal-700 px-3 py-2 font-bold text-white">Save and confirm</button>{(["amountMinor","currency","occurredAt","eventType","merchantLabel"] as const).map(f=>record.userOverrides[f]!==undefined&&<button key={f} type="button" onClick={()=>undo(f)} className="rounded border px-2 py-1 text-xs">Undo {f}</button>)}</div></form>}
